Numpydoc conversion of meas_algorithms through gaussianPsfFactory.py
lsst/meas_algorithms pull request #214
Opened 2020-10-22 21:15 UTC by squisty

2020-10-27 21:18 UTC, parejkoj requested changes
Thanks: a few comments, including correcting a non-building numbered list.

2020-10-27 21:18 UTC, parejkoj commented on python/lsst/meas/algorithms/gaussianPsfFactory.py
> +            config : ``lsst.pex.config.ConfigurableField``
The type here is `GaussianPsfFactory` (this class). I can see the confusion: this is a closure that is used by `ConfigurableField` to construct the correct kind of PSF, and so we're not documenting the return of `makeField` here. Keep the docstring as-written (even though it's sort of redundant).

2020-10-27 21:18 UTC, parejkoj commented on doc/lsst.meas.algorithms/tasks/lsst.meas.algorithms.FlaggedSourceSelectorTask.rst
> +to use the Sources to determine the PSF.
Lets change that to "to use those Sources", which I think clarifies the intent.

2020-11-07 01:22 UTC, squisty commented on doc/lsst.meas.algorithms/tasks/lsst.meas.algorithms.DynamicDetectionTask.rst
> +to identify good sky regions.
Fixed the sentence issue, the template for the task topic mentioned on https://developer.lsst.io/stack/task-topic-type.html#starter-template has blank lines in between so I will go off of that for now?

2020-11-11 01:29 UTC, parejkoj commented on doc/lsst.meas.algorithms/tasks/lsst.meas.algorithms.DynamicDetectionTask.rst
> +to identify good sky regions.
The numbered list generated correctly now.

2020-11-13 20:53 UTC, parejkoj approved these changes

2020-11-13 20:55 UTC, merged